In [3]:
import numpy as np
print("numpy is imported")

numpy is imported


In [4]:
ls = [41,52,63,96,85,74,523,14,47,58,69]
ls

[41, 52, 63, 96, 85, 74, 523, 14, 47, 58, 69]

In [5]:
arr = np.array(ls)
arr

array([ 41,  52,  63,  96,  85,  74, 523,  14,  47,  58,  69])

In [6]:
type(arr)

numpy.ndarray

In [9]:
arr.ndim  # no.of dimention 

#[25,41,63]
#[[],[],[]]     =>>>>> 2 D array

1

In [10]:
arr.dtype

dtype('int64')

In [24]:

ls = [41,52,63,96,85,74,523,14,47,58,69,'upflairs']
arr = np.array(ls)
arr 


array(['41', '52', '63', '96', '85', '74', '523', '14', '47', '58', '69',
       'upflairs'], dtype='<U21')

In [25]:
arr[2]

np.str_('63')

In [26]:

ls = [41,52,63,96,85,74,523,14,47,58,69,]
arr = np.array(ls)
arr 

array([ 41,  52,  63,  96,  85,  74, 523,  14,  47,  58,  69])

In [28]:
arr[3]

np.int64(96)

In [33]:
ls = [41,23,56,88,54,97,34,46,567,564,78,65,90,12,3]
arr = np.array(ls)
arr

array([ 41,  23,  56,  88,  54,  97,  34,  46, 567, 564,  78,  65,  90,
        12,   3])

In [34]:
arr[2:5:2]

array([56, 54])

In [35]:
arr

array([ 41,  23,  56,  88,  54,  97,  34,  46, 567, 564,  78,  65,  90,
        12,   3])

In [36]:
arr.size

15

In [37]:
len(arr) #polymorphism

15

In [38]:
arr

array([ 41,  23,  56,  88,  54,  97,  34,  46, 567, 564,  78,  65,  90,
        12,   3])

In [39]:
ls = [41,  23,  56,  88,  54,  97,  34,  46, 567, 564,  78,  65,  90, 12,   3]
arr = np.array(ls)
arr > 50
arr

array([ 41,  23,  56,  88,  54,  97,  34,  46, 567, 564,  78,  65,  90,
        12,   3])

In [40]:
arr
for i in ls:
    if i<50:
        print(i)

41
23
34
46
12
3


In [43]:
arr[arr<50]

array([41, 23, 34, 46, 12,  3])

In [45]:
arr

array([ 41,  23,  56,  88,  54,  97,  34,  46, 567, 564,  78,  65,  90,
        12,   3])

In [46]:
arr2 = np.arange(50)  # 1 d array
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
np.ones((10,5))    # 2d array


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
np.linspace(1,50,50)   # in between 1 to 8  write 5 item

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [59]:
import random 

In [67]:
random.randint(1,10)

3

In [108]:
random.random()

0.43614951824827686

In [110]:
ls = ['bhumika','pradeep','prabhu','pravika','divya','ayushi','bhagyashree']
ls

['bhumika', 'pradeep', 'prabhu', 'pravika', 'divya', 'ayushi', 'bhagyashree']

In [122]:
random.choice(ls)

'pradeep'

In [128]:
random.choices(ls)

['bhumika']

In [190]:
random.choices(ls,k=4)

['pravika', 'pradeep', 'bhumika', 'prabhu']

In [191]:
ls

['bhumika', 'pradeep', 'prabhu', 'pravika', 'divya', 'ayushi', 'bhagyashree']

In [192]:
random.shuffle(ls)

In [202]:
ls

['prabhu', 'ayushi', 'pradeep', 'pravika', 'bhumika', 'divya', 'bhagyashree']

In [208]:
np.random.randint(1,50,10)  # in b/w 1 to 50 random 10 item

array([34, 45, 39, 10, 32, 35, 35, 44, 14, 49], dtype=int32)

In [211]:
np.random.randint(1,50,(10,5))  

array([[10, 47,  9, 20, 30],
       [44, 18, 14, 45,  9],
       [ 7,  7, 16, 17, 36],
       [12,  7, 32, 48, 40],
       [ 1, 28, 17, 15, 29],
       [34, 41, 17, 45, 25],
       [26,  3, 28, 48, 22],
       [42, 26, 34,  9,  1],
       [26, 11, 21, 18, 28],
       [33,  6,  2,  3,  2]], dtype=int32)

In [215]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [221]:
arr.reshape(12,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [225]:
arr2 = np.resize(arr,(25,25))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [226]:
arr2.shape

(25, 25)

In [227]:
arr2.ndim

2

In [229]:
25*25

625

In [228]:
arr2.reshape(625,) # 2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [231]:
arr2.ravel() #1d 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [233]:
arr2.flatten() # flateen and revel both are same

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [1]:
import numpy as np 

In [3]:
arr = np.random.randint(5,50,100)
arr

array([15, 11, 10, 22, 47, 16, 43,  5, 31, 29, 27,  9, 28, 30, 35, 44, 27,
       31,  5, 34, 44, 28,  6,  8, 21, 12, 35, 40, 29, 35, 12, 27, 12, 40,
       22, 33, 27, 44, 29, 48,  8, 12, 42, 23, 23, 49, 42, 41,  8, 12, 27,
       22, 17, 38, 21, 33,  7, 29, 20, 39, 19, 46, 15, 27, 37, 46, 34,  5,
       46, 22, 38, 36, 25, 35, 29, 15, 11, 14, 11, 36, 29,  9, 22, 16, 25,
       25, 26, 32, 16, 26, 24, 43, 24, 30, 19, 38, 36, 29,  7, 17],
      dtype=int32)

In [4]:
arr.mean()   # mean is average 

np.float64(26.04)

In [5]:
arr = np.random.randint(5,50,(4,3))
arr

array([[47, 33, 15],
       [18, 18, 32],
       [44, 18, 17],
       [10, 10,  9]], dtype=int32)

In [6]:
arr.shape

(4, 3)

In [9]:
np.transpose(arr).shape

(3, 4)

In [10]:
arr.T

array([[47, 18, 44, 10],
       [33, 18, 18, 10],
       [15, 32, 17,  9]], dtype=int32)

In [67]:

arr = np.random.randint(2,12,(10,5))
arr

array([[ 9,  2,  2, 10,  6],
       [ 2,  5,  2,  8,  4],
       [ 6,  5,  5,  7,  3],
       [ 3,  7,  9,  3,  5],
       [11,  2,  3,  4,  2],
       [ 5, 10,  8,  4,  5],
       [ 6,  8,  4,  8,  6],
       [ 5,  3,  2,  9,  7],
       [ 9, 11,  3,  2,  8],
       [ 7, 11,  3,  8,  6]], dtype=int32)

In [21]:
arr[-1]

array([ 3, 10,  5,  8,  3], dtype=int32)

In [26]:
arr[7:]

array([[ 2, 11, 10,  6, 10],
       [ 2,  4,  5,  4,  5],
       [ 3, 10,  5,  8,  3]], dtype=int32)

In [29]:
arr[0:,0:2]

array([[11,  4],
       [ 3,  8],
       [ 6, 11],
       [ 9,  7],
       [ 8,  2],
       [ 6,  7],
       [ 3, 10],
       [ 2, 11],
       [ 2,  4],
       [ 3, 10]], dtype=int32)

In [30]:
arr[3:6,-3:]

array([[5, 6, 6],
       [5, 9, 2],
       [6, 9, 9]], dtype=int32)

In [32]:
arr[0:10:2,2:]

array([[10, 11,  4],
       [ 5,  7,  2],
       [ 5,  9,  2],
       [ 2,  7,  6],
       [ 5,  4,  5]], dtype=int32)

In [34]:
arr = np.random.randint(2,50,(5,10,5))
arr

array([[[32, 23, 41, 29, 42],
        [ 5, 42, 15,  3, 30],
        [ 8, 40, 32, 15, 38],
        [43, 43, 39, 22, 42],
        [24, 28, 28, 48, 30],
        [ 8, 46, 33,  4, 20],
        [44, 30, 34,  9, 14],
        [20, 29, 13, 25, 39],
        [13, 30, 36,  5, 16],
        [24, 22, 48,  8, 46]],

       [[18, 46, 37, 36,  7],
        [17, 31,  7, 41, 44],
        [20, 33, 20, 39, 36],
        [46, 34, 26, 37, 39],
        [31,  5, 27, 27, 24],
        [12, 30, 28, 36, 45],
        [23, 11, 48, 19, 17],
        [27, 47, 47,  2, 23],
        [14, 47, 39, 21, 40],
        [41,  4, 21, 36, 25]],

       [[22, 49, 20, 35, 28],
        [42, 41,  9, 36, 10],
        [42, 18,  2, 47, 43],
        [17, 31, 35, 15,  8],
        [15, 48,  7, 25, 39],
        [48,  9,  2, 32, 32],
        [44,  3, 19, 18, 35],
        [19, 24, 28,  9,  8],
        [14,  4, 44, 46, 21],
        [20, 32, 33, 43, 40]],

       [[10, 19, 10, 45, 36],
        [31,  5,  4,  9, 22],
        [48, 39, 13,  6, 24],
    

In [35]:
arr.shape

(5, 10, 5)

In [36]:
arr.ndim

3

In [37]:
arr[0]

array([[32, 23, 41, 29, 42],
       [ 5, 42, 15,  3, 30],
       [ 8, 40, 32, 15, 38],
       [43, 43, 39, 22, 42],
       [24, 28, 28, 48, 30],
       [ 8, 46, 33,  4, 20],
       [44, 30, 34,  9, 14],
       [20, 29, 13, 25, 39],
       [13, 30, 36,  5, 16],
       [24, 22, 48,  8, 46]], dtype=int32)

In [38]:
arr[1]

array([[18, 46, 37, 36,  7],
       [17, 31,  7, 41, 44],
       [20, 33, 20, 39, 36],
       [46, 34, 26, 37, 39],
       [31,  5, 27, 27, 24],
       [12, 30, 28, 36, 45],
       [23, 11, 48, 19, 17],
       [27, 47, 47,  2, 23],
       [14, 47, 39, 21, 40],
       [41,  4, 21, 36, 25]], dtype=int32)

In [39]:
arr[2]

array([[22, 49, 20, 35, 28],
       [42, 41,  9, 36, 10],
       [42, 18,  2, 47, 43],
       [17, 31, 35, 15,  8],
       [15, 48,  7, 25, 39],
       [48,  9,  2, 32, 32],
       [44,  3, 19, 18, 35],
       [19, 24, 28,  9,  8],
       [14,  4, 44, 46, 21],
       [20, 32, 33, 43, 40]], dtype=int32)

In [40]:
arr[3]

array([[10, 19, 10, 45, 36],
       [31,  5,  4,  9, 22],
       [48, 39, 13,  6, 24],
       [27, 35, 30, 11,  8],
       [39, 10, 47, 10, 47],
       [14, 46, 32,  7, 15],
       [36, 23, 20, 49, 35],
       [13,  4, 46, 23,  2],
       [ 3, 38, 12, 10, 22],
       [18, 25, 10,  6, 16]], dtype=int32)

In [41]:
arr[4]

array([[16, 23, 48, 41, 27],
       [36, 10, 43,  7, 38],
       [35, 34, 24, 10, 40],
       [29, 46, 43, 47, 47],
       [13, 47, 22, 33,  6],
       [38, 22, 46, 41, 35],
       [15, 45, 33, 41, 21],
       [34, 18, 37, 38, 46],
       [45,  4,  3, 25, 27],
       [31, 38, 21, 30, 36]], dtype=int32)

In [46]:
arr[0][7:8,2:]

array([[13, 25, 39]], dtype=int32)

In [52]:
arr[0:,9:,0:]

array([[[24, 22, 48,  8, 46]],

       [[41,  4, 21, 36, 25]],

       [[20, 32, 33, 43, 40]],

       [[18, 25, 10,  6, 16]],

       [[31, 38, 21, 30, 36]]], dtype=int32)

In [62]:
arr = np.array([7,5,9])
arr

array([7, 5, 9])

In [55]:
arr.max()

np.int64(9)

In [56]:
arr.argmax() # indexing of max no.

np.int64(2)

In [57]:
arr.argmin()

np.int64(1)

In [59]:
arr.sort()

In [60]:
arr

array([5, 7, 9])

In [63]:
arr[::-1]

array([9, 5, 7])

In [64]:
arr.argsort()    # 5    7    9

array([1, 0, 2])

In [65]:
arr

array([7, 5, 9])

In [68]:
arr = np.random.randint(2,12,(10,5))
arr

array([[ 5,  8,  8,  4,  7],
       [ 7,  5,  7,  4,  7],
       [ 6,  7,  6,  6,  8],
       [10,  8,  8,  7,  3],
       [10,  3,  3,  6,  5],
       [ 8,  7,  4,  3,  7],
       [ 4,  4,  5,  8,  8],
       [ 8,  9,  2,  4,  6],
       [ 8,  5, 10, 11,  7],
       [ 9,  6,  2,  4,  4]], dtype=int32)

In [69]:
np.unique(arr)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [70]:
np.random.randint(2,250,200)
arr

array([[ 5,  8,  8,  4,  7],
       [ 7,  5,  7,  4,  7],
       [ 6,  7,  6,  6,  8],
       [10,  8,  8,  7,  3],
       [10,  3,  3,  6,  5],
       [ 8,  7,  4,  3,  7],
       [ 4,  4,  5,  8,  8],
       [ 8,  9,  2,  4,  6],
       [ 8,  5, 10, 11,  7],
       [ 9,  6,  2,  4,  4]], dtype=int32)

In [72]:
np.median(arr)

np.float64(6.5)

In [75]:
arr.std()

np.float64(2.2026347858871205)

In [76]:
np.sqrt(25)

np.float64(5.0)

In [78]:
arr.var()

np.float64(4.851600000000001)

In [ ]:
#numpy

In [79]:
#pandas
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB 660.6 kB/s eta 0:00:18
   ---------------------------------------- 0.0/11.5 MB 487.6 kB/s eta 0:00:24
   ---------------------------------------- 0.1/11.5 MB 737.3 kB/s eta 0:00:16
    --------------------------------------- 0.2/11.5 MB 984.6 kB/s eta 0:00:12
    --------------------------------------- 0.2/11.5 MB 908.0 kB/s eta 0:00:13
    --------------------------------------- 0.3/11.5 MB 1.1 MB/s eta 0:00:11
   - -------------------------------------- 0.3/11.5 MB 1.1 MB/s eta 0:00:11
   - -------------------------------------- 0.3/11.5 MB 1.1 MB/s eta 0:00:11
   - -------------------------------------- 0.4/11.5 MB 969.8 kB/s eta 0:00:12
   - -------------------------------------- 0.4/11.5 MB 946.4 kB/s eta 0:00:12
   - -------------------------------------- 0.5/11.5 MB 982.5 kB/s e

In [80]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [81]:
import pandas as pd
print("imported")

imported
